app:
  fullName: application-be-stag
  name: application
  type: be
  env: stag

container:
  port: 8080
  image:
    registry: 067347400935.dkr.ecr.ap-northeast-2.amazonaws.com
    version: 307a2a606d5ce02c2435d592c549faa6399be636

ingress:
  host: stag-api.xquare.app
  prefix: /applications
