app:
  fullName: application-be-stag
  name: application
  type: be
  env: stag

container:
  port: 8080
  image:
    registry: 067347400935.dkr.ecr.ap-northeast-2.amazonaws.com
    version: 9b3c88bec6894d91418bad2e1d4539e5a1bc77f7

ingress:
  host: stag-api.xquare.app
  prefix: /applications
