app: 
  fullName: schedule-be-stag
  name: schedule
  type: be
  env: stag

container:
  port: 8080
  image:
    registry: 067347400935.dkr.ecr.ap-northeast-2.amazonaws.com
    version: 2dbace4d1bf9fc1f1ebb7eb9db4bceecd3518a8c

ingress:
  host: stag-api.xquare.app
  prefix: /schedules
