app: 
  fullName: schedule-be-stag
  name: schedule
  type: be
  env: stag

container:
  port: 8080
  image:
    registry: 067347400935.dkr.ecr.ap-northeast-2.amazonaws.com
    version: 63d78902f158cdd77008b5f253b9dca49f0ed521

ingress:
  host: stag-api.xquare.app
  prefix: /schedules
