app:
  fullName: attachment-be-stag
  name: attachment
  type: be
  env: stag

container:
  port: 8080
  image:
    registry: 067347400935.dkr.ecr.ap-northeast-2.amazonaws.com
    version: f0bdf51ea3aa89c21b0dc62f9bc052ef2453ef85

ingress:
  host: stag-api.xquare.app
  prefix: /attachment
