app: 
  fullName: report-be-stag
  name: report
  type: be
  env: stag

container:
  port: 8080
  image:
    registry: 067347400935.dkr.ecr.ap-northeast-2.amazonaws.com
    version: 54f88b42458bd9dda17e469df39cba777fc91cd0

ingress:
  host: stag-api.xquare.app
  prefix: /reports
