app:
  fullName: notification-be-stag
  name: notification
  type: be
  env: stag

container:
  port: 8080
  image:
    registry: 067347400935.dkr.ecr.ap-northeast-2.amazonaws.com
    version: b90996d2ebf39d09c230516bca2920374fbf7b3f

ingress:
  host: stag-api.xquare.app
  prefix: /notifications
